"""Add lamoda fields to items

Revision ID: 7ac61a8d8408
Revises: 57fe8863cb14
Create Date: 2025-06-30 07:45:05.662523

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '7ac61a8d8408'
down_revision = '57fe8863cb14'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('source', sa.String(length=50), nullable=True))
    op.add_column('items', sa.Column('source_url', sa.String(length=500), nullable=True))
    op.add_column('items', sa.Column('source_sku', sa.String(length=100), nullable=True))
    op.add_column('items', sa.Column('old_price', sa.Float(), nullable=True))
    op.create_index(op.f('ix_items_source'), 'items', ['source'], unique=False)
    op.create_index(op.f('ix_items_source_sku'), 'items', ['source_sku'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_source_sku'), table_name='items')
    op.drop_index(op.f('ix_items_source'), table_name='items')
    op.drop_column('items', 'old_price')
    op.drop_column('items', 'source_sku')
    op.drop_column('items', 'source_url')
    op.drop_column('items', 'source')
    # ### end Alembic commands ### 